### PR TITLE
Add check for services that should be running to maintenance status

### PR DESCRIPTION
**Pull request by rubo77**
When you call

    maintenance status

This will add a check for all services that should be running

### CODE REVIEW

**Comment by rubo77** [comment]
enahncements could be a unified display in a kind of table and colorization (green and red)

**Comment by rubo77** [comment]
i appended the changes so the output is consistent and colorized

**Comment by sargon** [comment]
I don't think it is the job of the maintenance script todo any checks of that sort.
To clarify the job is to mark the machine to be in maintenance and to stop the service that prevent maintenance. Further kicking of client is better to be done by hand and only to be done when you know what you are doing.

**Comment by rubo77** [comment]
Where would such a script to be in the right place?

another script in /usr/local/bin ?

**Comment by sargon** [comment]
Yo.

**Comment by rubo77** [comment]
https://github.com/ffnord/ffnord-puppet-gateway/pull/127

**Pull request closed without merging**
