### PR TITLE
vpn: add generic openvpn profile

### PR DESCRIPTION
**Pull request by sargon**
Add generic openvpn support, for providers not official supported.

### CODE REVIEW

**Comment by do9xe** [comment]
with this you could also solve #9 .
The rest looks fine to me. I will merge it when you dont want to solve #9

**Comment by sargon** [comment]
This generic openvpn profile is mainly for those providers we do not support directly, it would recommend that we build in providers directly to support them directly, encapsulate and handle special case handling. The main purpose for introducing this profile is the service host in the generic-example, which is hand build and only for simulation purposes.

**Comment by sargon** [comment]
Could someone please make a code review ... ?

**Comment by do9xe** [comment]
I did a code review already, just waited about the #9 thing ;)

**Pull request merged**
