### PR TITLE
Revert "Add Travis CI Config for validating puppet module v2"

### PR DESCRIPTION
**Pull request by do9xe**
As we did NOT discuss this in any manner I'd like to revert ffnord/ffnord-puppet-gateway#149 .
This is not, what creating pull-requests is about! We need to talk about this, especially, if it is something like this, were we need an account.

### CODE REVIEW

**Comment by MTRNord** [comment]
+1
That was not what I planned with the Pull ;) that was definitely a pull request that have to be diiscussed before,

**Comment by rubo77** [comment]
Since it is not intruding the rest of the code, I merged it to try it out if we would benefit from the travis check. I have a travis account and could add the checks if needed.
If it is a useless tool that noone benefits, we can leave this reverted ;)

**Comment by sargon** [comment]
I vote for revert.

**Comment by ohrensessel** [comment]
we should first see whether we benefit from the travis stuff, then merge such a thing.
in general I think travis is quite helpful to ensure that syntactical errors are spotted early.

**Comment by MTRNord** [comment]
@ohrensessel that was why I made the pull ;) but I don't know how save the tests are. i can't check if the data of it is valid. So I think tests are really needed and they should be running a few weeks. Than it is possible to see if the validation is right

**Pull request closed without merging**
