### PR TITLE
Add second fastd instance with MTU 1280

### PR DESCRIPTION
**Pull request by rubo77**
to circumvent unstable connections with Kabel Deutschland

### CODE REVIEW

**Comment by ohrensessel** [comment]
Thanks for your effort. I would, however, like to see this more flexible. Now we have the possibility to support two music, but in case of a mtu change we might to need support e.g. three instances. Because of that it would be great if we would have the possibility to support multiple fastd instances (not only two), maybe by just giving a list of mtus and ports. 

This also would be a great preparation for separate fastd instances for node and inter-gateway traffic.

**Comment by ohrensessel** [comment]
Two music = two mtus. Stupid autocorrect.

**Comment by rubo77** [comment]
Is there anything missing in this setup? If not, you can accept this for a start and I will create another patch these days, that will replace the identifyer string "low" with a configurable string, for each instance in a list of mtus, identifyer strings  and ports.

**Comment by sargon** [comment]
This patch-set didn't solve the generic problem of multiple fastd instances per community, it rater introduce further special cases, which we afterwords have to clean up. I rate against a merge.

**Comment by rubo77** [comment]
I have to find out  how to [create a file for each defined block with puppet](http://stackoverflow.com/questions/30157708/create-a-file-for-each-defined-block-with-puppet)

**Comment by rubo77** [comment]
I created another aproach here: https://github.com/rubo77/ffnord-example/commits/multiple_fastd which uses the branch https://github.com/rubo77/ffnord-puppet-gateway/tree/multi_fastd 

Can someone please test this if it is ok like this?

**Comment by rubo77** [comment]
new PR: #120

**Pull request closed without merging**
