### PR TITLE
Add Travis ci Config for validating puppet module

### PR DESCRIPTION
**Pull request by MTRNord**
Add an Travis Ci script based on @pinguinpfleger in #144 

But be aware that puppet-lint is giving a lot of errors. I did use as Test.pp the puppet script from the README.md and did not change anything in the bash script by @pinguinpfleger

If any of the Admins wanna make this validation trough Travis CI: here is the code for it ;) Tested and working.

### CODE REVIEW

**Comment by MTRNord** [comment]
For adding this here are pro and contra:

Pro:
- You can add a badge how the state of the build is

Contra:
- one of the admins have to login to https://travis-ci.org and must activate the repo there

**Comment by rubo77** [comment]
please rework to just one commit "ading travis"

**Comment by MTRNord** [comment]
@rubo77 new pull at #149

**Comment by rubo77** [comment]
What about the the testGW.pp?

**Comment by MTRNord** [comment]
@rubo77 it was not needed. it was just the pp of the README and is not needed to use the script :)

**Pull request closed without merging**
